---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apr-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apr
        component: web
        layer: application
      name: apr-web
    spec:
      containers:
      - name: apr-web
        env:
        - name: MIX_ENV
          value: prod
        - name: PORT
          value: '4000'
        envFrom:
        - configMapRef:
            name: apr-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/apr:production
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apr
    component: web
    layer: application
  name: apr-web
  namespace: default
  annotations:
    annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 4000
  - port: 80
    protocol: TCP
    name: http
    targetPort: 4000
  selector:
    app: apr
    component: web
    layer: application
  type: LoadBalancer
