---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apr-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apr
        layer: application
        component: web
      name: apr-web
      namespace: default
    spec:
      containers:
        - name: apr-web
          envFrom:
          - configMapRef:
              name: apr-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/apr:staging
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apr
    layer: application
    component: web
  name: apr-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: apr
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
