---
version: '2'
services:
  apr:
    command: mix test
    environment:
    - MIX_ENV=test
    - RABBITMQ_HOST=apr-rabbitmq
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    - RABBITMQ_PORT=5672
    - BASIC_AUTH_USER=sample
    - BASIC_AUTH_PASSWORD=sample
    extends:
      file: common.yml
      service: apr
    depends_on:
      - apr-rabbitmq
  apr-rabbitmq:
    image: rabbitmq:3.6-management
